version: '3'

services:
  mariadb:
    image: mariadb:10.4
    container_name: vivo_db
    environment:
      - MYSQL_USER=vitrodbUsername
      - MYSQL_PASSWORD=vitrodbPassword
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_ROOT_HOST=%
      - TZ=America/New_York
    volumes:
      - db_data:/var/lib/mysql
      - ./db_autoimport:/docker-entrypoint-initdb.d/
    restart: always

  solr:
    container_name: vivo_solr
    build:
      context: ./solr
    ports:
      - 8983:8983
    depends_on:
      - mariadb
    volumes:
      - solr_data:/opt/solr/server/solr/ckan/data
    command: solr-create -c vivocore -d /opt/vivocore
    restart: always

  vivo:
    container_name: vivo
    build:
      context: ./vivo
    depends_on:
      - solr
      - mariadb
    volumes:
      - ./vivo/applicationSetup.n3:/usr/local/VIVO/home/config/applicationSetup.n3
      - ./vivo/log4j.properties:/usr/local/tomcat/webapps/VIVO/WEB-INF/classes
      - ./vivo/runtime.properties:/usr/local/VIVO/home/config/runtime.properties
      # surprising that the running theme is in /tomcat/ when the Dockerfile puts it in /webapp/target/
      # java must be moving the folder during the container build
      - ./vivo/uncw_theme:/usr/local/tomcat/webapps/vivo/themes/uncw_theme
    ports:
      - 8080:8080
    restart: always

volumes:
  solr_data:
  db_data:
