version: '3.7'

services:
  solr:
    container_name: solr
    build:
      context: ./solr
    restart: always

  vivo:
    container_name: vivo
    build:
      context: ./vivo
    depends_on:
      - solr
    volumes:
      - ./tdbModels:/usr/local/VIVO/home/tdbModels
      - ./tdbContentModels:/usr/local/VIVO/home/tdbContentModels
      - ./vivo/custom_theme:/usr/local/tomcat/webapps/ROOT/themes/custom_theme
    ports:
      - 8080:8080
    restart: always
