version: '3'

services:
  solr:
    container_name: solr
    image: libapps-admin.uncw.edu:8000/randall-dev/vivo-docker2/solr
    build:
      context: ./solr
    restart: always

  vivo:
    container_name: vivo
    image: libapps-admin.uncw.edu:8000/randall-dev/vivo-docker2/vivo
    build:
      context: ./vivo
    depends_on:
      - solr
    volumes:
      - tbdModels:/usr/local/VIVO/home/tdbModels
      - tbdContentModels:/usr/local/VIVO/home/tdbContentModels
      - ./vivo/uncw_theme:/usr/local/tomcat/webapps/vivo/themes/uncw_theme
    ports:
      - 8080:8080
    restart: always

volumes:
  tbdModels:
  tbdContentModels:
